---

detectors:
  IrresponsibleModule:
    enabled: false

  NestedIterators:
    exclude:
      - DnsMock::Server::RecordsDictionaryBuilder#build

  UtilityFunction:
    exclude:
      - DnsMock::Server::RecordsDictionaryBuilder#build_records_instances_by_type
      - DnsMock::RspecHelper::RecordsDictionary#hostname_records_by_type
      - DnsMock::RspecHelper::DnsMessage#to_dns_name
      - DnsMock::RspecHelper::ContextGenerator#random_dns_record_type
      - DnsMock::RspecHelper::ContextGenerator#random_hostname
      - DnsMock::RspecHelper::ContextGenerator#create_dns_name
      - DnsMock::RspecHelper::ContextGenerator#random_ip_v4_address
      - DnsMock::RspecHelper::ContextGenerator#random_ip_v6_address
      - DnsMock::RspecHelper::ContextGenerator#random_txt_record_context
      - DnsMock::RspecHelper::ContextGenerator#to_punycode_hostname
      - DnsMock::RspecHelper::RecordsDictionary#create_records_dictionary_by_records
      - DnsMock::RspecHelper::Server#start_random_server
      - DnsMock::RspecHelper::Server#stop_all_running_servers
      - DnsMock::RspecHelper::ContextGenerator#random_port_number
      - DnsMock::TestFramework::RSpec::Helper#dns_mock_server
      - DnsMock::RspecHelper::ContextGenerator#to_rdns_hostaddress

  DuplicateMethodCall:
    exclude:
      - DnsMock::RspecHelper::ContextGenerator#create_records

  ControlParameter:
    exclude:
      - DnsMock::Error::Helper#raise_unless
      - DnsMock::Server#initialize
      - DnsMock::RspecHelper::ContextGenerator#to_punycode_hostname

  MissingSafeMethod:
    exclude:
      - DnsMock::RspecHelper::PortInUse::TransportService
      - DnsMock::Server

  TooManyStatements:
    exclude:
      - DnsMock::Server::RecordsDictionaryBuilder#build
      - DnsMock::Server#initialize
      - DnsMock::Server#run

  TooManyInstanceVariables:
    exclude:
      - DnsMock::Server

  LongParameterList:
    exclude:
      - DnsMock::Server#initialize
      - DnsMock#start_server

  BooleanParameter:
    exclude:
      - DnsMock::Server#initialize
      - DnsMock#start_server

  NilCheck:
    exclude:
      - DnsMock::Record::Builder::Mx#build
