detectors:
  IrresponsibleModule:
    enabled: false

  NestedIterators:
    exclude:
      - DnsMock::Server::RecordsDictionaryBuilder#build

  UtilityFunction:
    exclude:
      - DnsMock::Server::RecordsDictionaryBuilder#build_records_instances_by_type
      - DnsMock::RecordsDictionaryHelper#hostname_records_by_type
      - DnsMock::DnsMessageHelper#to_dns_name
      - DnsMock::ContextGeneratorHelper#random_dns_record_type
      - DnsMock::ContextGeneratorHelper#random_hostname
      - DnsMock::ContextGeneratorHelper#create_dns_name
      - DnsMock::ContextGeneratorHelper#random_ip_v4_address
      - DnsMock::ContextGeneratorHelper#random_ip_v6_address
      - DnsMock::ContextGeneratorHelper#random_txt_record_context
      - DnsMock::RecordsDictionaryHelper#create_records_dictionary_by_records
      - DnsMock::ServerHelper#start_random_server
      - DnsMock::ServerHelper#stop_all_running_servers
      - DnsMock::Server::RecordsDictionaryBuilder#rdns_lookup_prefix
      - DnsMock::ContextGeneratorHelper#random_port_number
      - DnsMock::TestFramework::RSpec::Helper#dns_mock_server

  ControlParameter:
    exclude:
      - DnsMock::Error::Helper#raise_unless
      - DnsMock::Server#initialize

  MissingSafeMethod:
    exclude:
      - DnsMock::PortInUseHelper::TransportService
      - DnsMock::Server

  TooManyStatements:
    exclude:
      - DnsMock::Server::RecordsDictionaryBuilder#build
      - DnsMock::Server#initialize
      - DnsMock::Server#run

  TooManyInstanceVariables:
    exclude:
      - DnsMock::Server

  LongParameterList:
    exclude:
      - DnsMock::Server#initialize
      - DnsMock#start_server

  BooleanParameter:
    exclude:
      - DnsMock::Server#initialize
      - DnsMock#start_server

  NilCheck:
    exclude:
      - DnsMock::Record::Builder::Mx#build
