detectors:
  IrresponsibleModule:
    enabled: false

  NestedIterators:
    exclude:
      - DnsMock::RecordsDictionaryBuilder#build

  UtilityFunction:
    exclude:
      - DnsMock::RecordsDictionaryBuilder#build_records_instances_by_type
      - DnsMock::RecordsDictionaryHelper#hostname_records_by_type
      - DnsMock::RecordsDictionaryHelper#random_hostname

  ControlParameter:
    exclude:
      - DnsMock::Helper::Error#raise_record_type_error
