detectors:
  IrresponsibleModule:
    enabled: false

  NestedIterators:
    exclude:
      - DnsMock::Server::RecordsDictionaryBuilder#build

  UtilityFunction:
    exclude:
      - DnsMock::Server::RecordsDictionaryBuilder#build_records_instances_by_type
      - DnsMock::RecordsDictionaryHelper#hostname_records_by_type
      - DnsMock::DnsMessageHelper#to_dns_name
      - DnsMock::ContextGeneratorHelper#random_dns_record_type
      - DnsMock::ContextGeneratorHelper#random_hostname
      - DnsMock::ContextGeneratorHelper#create_dns_name

  ControlParameter:
    exclude:
      - DnsMock::Helper::Error#raise_record_type_error
