detectors:
  IrresponsibleModule:
    enabled: false

  NestedIterators:
    exclude:
      - DnsMock::Server::RecordsDictionaryBuilder#build

  UtilityFunction:
    exclude:
      - DnsMock::Server::RecordsDictionaryBuilder#build_records_instances_by_type
      - DnsMock::RecordsDictionaryHelper#hostname_records_by_type
      - DnsMock::DnsMessageHelper#to_dns_name
      - DnsMock::ContextGeneratorHelper#random_dns_record_type
      - DnsMock::ContextGeneratorHelper#random_hostname
      - DnsMock::ContextGeneratorHelper#create_dns_name
      - DnsMock::ContextGeneratorHelper#random_ip_v4_address
      - DnsMock::ContextGeneratorHelper#random_ip_v6_address
      - DnsMock::ContextGeneratorHelper#random_txt_record_context

  TooManyStatements:
    exclude:
      - DnsMock::Server::RecordsDictionaryBuilder#build

  ControlParameter:
    exclude:
      - DnsMock::Error::Helper#raise_unless

  MissingSafeMethod:
    exclude:
      - DnsMock::PortInUseHelper::TransportService
